import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <React.StrictMode>
      <html lang="en">
        <body
        >
          <div className="max-w-[1280px] px-[15px] w-full mx-auto">
            <Header />
            {children}
          </div>
        </body>
      </html>
    </React.StrictMode>
  );
}
